const userOne = {
  "username": "joakimonline",
  "password": "hejhej123",
  "firstname": "joakim",
  "lastname": "andersson",
  "image": "https://res.cloudinary.com/climb/image/upload/c_fill,f_auto,h_800,q_80/v1529156695/smdkhkjp4g9yahs0afbx",
  "city": "oslo",
  "address": "kirkegata 12",
  "gender": "male",
  "genderinterests": "male",
  "interests": ["sport", "gym", "fotboll", "tv", "fashion"],
  "description": "snill gogutt",
  "email": "joakim.andersson@teknologi.se",
  "phone": 12345,
  "birthday": 18 - 03 - 1993,
  "friends": ["Georg Ekeberg", "Na Wei"],
  "groups": [],
  "events": [],
  "date": Date,
  "disabilities": [],
  "objectId": objectID,
  "governmentId": 55511221,
};

const userTwo = {
  "username": "helarionline",
  "password": "hello123",
  "firstname": "helari",
  "lastname": "sosi",
  "image": "https://media-exp1.licdn.com/dms/image/C4D03AQFC7chaWouVtg/profile-displayphoto-shrink_800_800/0?e=1611792000&v=beta&t=mqQNLO_3vuoK1bVxlV5SAYcLUZw4tATmCSjbUlcHAs0",
  "city": "stavanger",
  "address": null,
  "gender": "male",
  "genderinterests": "female",
  "interests": ["interior", "gym", "fotboll", "gaming", "dance"],
  "description": "kul fyr fra utlandet",
  "email": "helari.sosi@teknologi.se",
  "phone": 23456,
  "birthday": 18031993,
  "friends": ["Adrian Nesvik"],
  "groups": [],
  "events": [],
  "date": Date,
  "disabilities": [],
  "objectId": objectID,
  "governmentId": 55511222,
};

const userThree = {
  "username": "adrianonline",
  "password": "123hej",
  "firstname": "adrian",
  "lastname": "nesvik",
  "image": "https://media-exp1.licdn.com/dms/image/C4D03AQGnuyLd9dGlEw/profile-displayphoto-shrink_100_100/0?e=1609372800&v=beta&t=SSMoHRM64dKzdrMsB-Ir49zGbE6zYFzP0rUgG7BQrJU",
  "city": "stavanger",
  "address": "bakkeveien 321",
  "gender": "male",
  "genderinterests": "female",
  "interests": ["piano", "running", "fotboll", "gaming", "coding"],
  "description": "fyr mmed fin dialekt",
  "email": "adrian.nesvik@teknologi.se",
  "phone": 34567,
  "birthday": Date,
  "friends": ["Helari Sosi"],
  "groups": [],
  "events": [],
  "date": Date,
  "disabilities": [],
  "objectId": objectID,
  "governmentId": 55511223,
};

const userFour = {
  "username": "georgonline",
  "password": "123hello",
  "firstname": "georg",
  "lastname": "ekeberg",
  "image": "https://i1.rgstatic.net/ii/profile.image/531201853476865-1503659799653_Q512/Georg_Ekeberg.jpg",
  "city": "stavanger",
  "address": null,
  "gender": "male",
  "genderinterests": null,
  "interests": ["beer", "party", "fotboll", "gaming", "singing"],
  "description": "gutt fra landet",
  "email": "georg.ekeberg@teknologi.se",
  "phone": 45678,
  "birthday": Date,
  "friends": ["Joakim Andersson"],
  "groups": [],
  "events": [],
  "date": Date,
  "disabilities": [],
  "objectId": objectID,
  "governmentId": 55511224,
};

const userFive = {
  "username": "naonline",
  "password": "tjena123",
  "firstname": "na",
  "lastname": "wei",
  "image": "https://media-exp1.licdn.com/dms/image/C4E03AQGVzS9yUzvPyg/profile-displayphoto-shrink_800_800/0/1605802167386?e=1611792000&v=beta&t=BHniTi-lRaSIfNaP3ptU7qMLhWvgBNOiFfACpr8-2jY",
  "city": "melbourne",
  "address": null,
  "gender": "female",
  "genderinterests": "male",
  "interests": ["plants", "food", "running", "movies", "singing"],
  "description": "awesome girl",
  "email": "na.wei@teknologi.se",
  "phone": 56789,
  "birthday": Date,
  "friends": ["Joakim Andersson"],
  "groups": [],
  "events": [],
  "date": Date,
  "disabilities": [],
  "objectId": objectID,
  "governmentId": 55511225,
};